"""add codigo_estelar to estrela

Revision ID: d2eacdd904e6
Revises: 
Create Date: 2026-07-28 13:35:14.579408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2eacdd904e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estrelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('codigo_estelar', sa.String(), nullable=True),
    sa.Column('tipo_espectral', sa.String(), nullable=True),
    sa.Column('massa', sa.Float(), nullable=True),
    sa.Column('temperatura', sa.Integer(), nullable=True),
    sa.Column('idade_bilhoes_anos', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_estelar')
    )
    op.create_index(op.f('ix_estrelas_id'), 'estrelas', ['id'], unique=False)
    op.create_index(op.f('ix_estrelas_nome'), 'estrelas', ['nome'], unique=True)
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('raio_km', sa.Float(), nullable=True),
    sa.Column('habitavel', sa.Integer(), nullable=True),
    sa.Column('periodo_orbital_dias', sa.Float(), nullable=True),
    sa.Column('estrela_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estrela_id'], ['estrelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planetas_id'), 'planetas', ['id'], unique=False)
    op.create_index(op.f('ix_planetas_nome'), 'planetas', ['nome'], unique=True)
    op.create_table('meteoros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('composicao', sa.String(), nullable=True),
    sa.Column('velocidade_km_s', sa.Float(), nullable=True),
    sa.Column('massa_kg', sa.Float(), nullable=True),
    sa.Column('tamanho_metros', sa.Float(), nullable=True),
    sa.Column('estrela_id', sa.Integer(), nullable=True),
    sa.Column('planeta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estrela_id'], ['estrelas.id'], ),
    sa.ForeignKeyConstraint(['planeta_id'], ['planetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meteoros_id'), 'meteoros', ['id'], unique=False)
    op.create_index(op.f('ix_meteoros_nome'), 'meteoros', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meteoros_nome'), table_name='meteoros')
    op.drop_index(op.f('ix_meteoros_id'), table_name='meteoros')
    op.drop_table('meteoros')
    op.drop_index(op.f('ix_planetas_nome'), table_name='planetas')
    op.drop_index(op.f('ix_planetas_id'), table_name='planetas')
    op.drop_table('planetas')
    op.drop_index(op.f('ix_estrelas_nome'), table_name='estrelas')
    op.drop_index(op.f('ix_estrelas_id'), table_name='estrelas')
    op.drop_table('estrelas')
    # ### end Alembic commands ###
